#!/usr/bin/env python3
"""Logix cross-platform installer (system-wide).

Installs the Logix *core* — the logging bridge, the report generator, and the
read-only SQL helper — to a system location, initializes the SQLite schema,
and prints the per-OS steps to wire up capture.

  Linux/macOS:  sudo python3 install/install.py
  Windows:      (elevated PowerShell)  python install\\install.py

Stdlib only; no third-party dependencies. Run it again any time to upgrade the
installed core in place — it never clobbers an existing config.env or database.

Scope note: this installs the cross-platform core (which runs natively on all
three OSes) and, on Linux/macOS, generates an SSH login hook. The physical
"at-keyboard" sign-in popup is Windows-only (see windows/) and is not installed
here.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "logix"
sys.path.insert(0, str(SRC))
import paths  # noqa: E402  (resolved from SRC above — single source of truth)

CORE_FILES = [
    "paths.py",
    "log_physical.py",
    "logbook_report.py",
    "logbook_sql.py",
    "logbook_ssh_login.py",
]


def starter_config(dest: Path) -> str:
    return (
        f"# Logix config - system install at {dest}\n"
        f"# Parsed directly by logix/paths.py on every OS (no shell `source` needed).\n"
        f"# Environment variables override anything set here.\n"
        f'LOGIX_HOME={dest}\n'
        f'# LOGIX_DB={dest / "logix.db"}\n'
        f'# LOGBOOK_REPORT_DIR={dest / "reports"}\n'
    )


def write_ssh_hook(dest: Path, python: str) -> Path:
    """Generate a POSIX SSH login hook pointing at this install. Quoted so it
    survives install paths with spaces (e.g. macOS Application Support)."""
    login = dest / "logbook_ssh_login.py"
    hook = dest / "logix-ssh-hook.sh"
    hook.write_text(
        "#!/bin/bash\n"
        "# Logix: log an interactive SSH login once per session. Generated by install.py.\n"
        'case "$-" in *i*) ;; *) return 0 2>/dev/null || exit 0 ;; esac\n'
        'if [ -n "$SSH_CONNECTION" ] && [ -z "$LOGBOOK_SSH_LOGGED" ]; then\n'
        "    export LOGBOOK_SSH_LOGGED=1\n"
        '    export COMPCHEM_SESSION_TYPE="SSH"\n'
        '    export LOGBOOK_SESSION_ID="ssh-${USER:-unknown}-$$-$(date +%s)"\n'
        f'    if [ -x "{login}" ]; then\n'
        f'        ( "{python}" "{login}" >/dev/null 2>&1 & )\n'
        "    fi\n"
        'elif [ -z "$COMPCHEM_SESSION_TYPE" ]; then\n'
        '    export COMPCHEM_SESSION_TYPE="LOCAL"\n'
        "fi\n",
        encoding="utf-8",
    )
    os.chmod(hook, 0o755)
    return hook


def print_next_steps(dest: Path, hook: Path | None) -> None:
    db = dest / "logix.db"
    bar = "-" * 60
    print(f"\n{bar}\nInstalled. Database: {db}\n{bar}")
    print("\nVerify logging + reporting (works on every OS):")
    print(f'  python "{dest / "logbook_sql.py"}" "select count(*) from physical_log"')
    print(f'  python "{dest / "logbook_report.py"}"      # writes an .xlsx into {dest / "reports"}')

    if sys.platform.startswith("win"):
        print("\nPhysical (at-keyboard) capture on Windows:")
        print("  Use the WPF popup in windows/ - run windows\\install_logbook_tasks.ps1")
        print("  (elevated) to register the lock/unlock sign-in. It writes to this same DB.")
    else:
        print("\nSSH capture — install the generated hook:")
        if sys.platform == "darwin":
            print(f'  echo \'source "{hook}"\' | sudo tee -a /etc/zprofile   # or /etc/profile')
        else:
            print(f"  sudo ln -sf '{hook}' /etc/profile.d/zz_logbook_ssh.sh")
        print("  New interactive SSH logins will then be recorded automatically.")
    print()


def main() -> int:
    dest = paths._system_data_home()
    reports = dest / "reports"
    print(f"Logix installer - platform={sys.platform}")
    print(f"Install dir: {dest}")

    try:
        dest.mkdir(parents=True, exist_ok=True)
        reports.mkdir(parents=True, exist_ok=True)
    except PermissionError:
        print(
            f"\nPermission denied creating {dest}.\n"
            "Re-run with elevated privileges: sudo on Linux/macOS, "
            "an Administrator shell on Windows.",
            file=sys.stderr,
        )
        return 1

    for f in CORE_FILES:
        shutil.copy2(SRC / f, dest / f)
        print(f"  copied {f}")

    cfg = dest / "config.env"
    if cfg.exists():
        print(f"  kept existing {cfg.name}")
    else:
        cfg.write_text(starter_config(dest), encoding="utf-8")
        print(f"  wrote {cfg.name}")

    env = dict(os.environ, LOGIX_HOME=str(dest))
    r = subprocess.run([sys.executable, str(dest / "log_physical.py"), "--migrate"], env=env)
    if r.returncode != 0:
        print("ERROR: schema migration failed.", file=sys.stderr)
        return r.returncode
    print(f"  initialized {(dest / 'logix.db').name}")

    hook = None if sys.platform.startswith("win") else write_ssh_hook(dest, sys.executable)
    if hook:
        print(f"  wrote {hook.name}")

    print_next_steps(dest, hook)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
