#!/usr/bin/env python3
"""Prepare a Logix server for production, and pre-register its workstations.

Deliberately does NOT reuse a development database. A dev DB carries load-test
devices, test sessions with real names and NIMs, and enrolment keys that have
been sitting in a working tree -- none of which should exist on a server that
handles real students' data. This starts a clean one and refuses to overwrite
an existing DB unless told to.

Usage
-----
  # 1. Generate secrets and a clean DB
  python ops/go_live.py init --admin-email you@campus.ac.id

  # 2. Pre-register the lab, one line per station (hostname[,display name])
  python ops/go_live.py register --devices stations.txt

  # 3. Once every station has enrolled, close the door behind them
  python ops/go_live.py lockdown

  # At any time
  python ops/go_live.py check

`register` issues an invite pinned to each hostname, so a code can only ever
be redeemed by the machine it was cut for. Codes expire in 15 minutes, so run
it when you are ready to walk the lab -- or re-run it per batch.
"""
from __future__ import annotations

import argparse
import os
import secrets
import sqlite3
import sys
from datetime import datetime, timedelta
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SERVER = REPO / "server"
ENV_PATH = SERVER / ".env.production"
DB_PATH = SERVER / "central_logix.db"

# Anything below this is not worth calling a password on a box that holds
# student records.
MIN_PASSWORD_LEN = 20


def _c(text: str, code: str) -> str:
    return f"\033[{code}m{text}\033[0m" if sys.stdout.isatty() else text


ok = lambda s: print(f"  {_c('OK', '32')}   {s}")
warn = lambda s: print(f"  {_c('WARN', '33')} {s}")
bad = lambda s: print(f"  {_c('FAIL', '31')} {s}")


def _read_env(path: Path) -> dict:
    out = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                out[k.strip()] = v.strip()
    return out


def cmd_init(ns) -> int:
    if DB_PATH.exists() and not ns.force:
        bad(f"{DB_PATH} already exists.")
        print(
            "\n  A development database must never become a production one: it holds\n"
            "  load-test devices, test sessions with real names/NIMs, and keys that\n"
            "  have been sitting in a working tree.\n\n"
            f"  Move it aside and re-run, or pass --force to archive it automatically."
        )
        return 1

    if DB_PATH.exists():
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        archived = DB_PATH.with_name(f"{DB_PATH.stem}.pre-golive-{stamp}.db")
        DB_PATH.rename(archived)
        warn(f"existing database archived to {archived.name}")

    # Import after the DB has been moved so the schema is created fresh.
    sys.path.insert(0, str(SERVER))
    os.environ.setdefault("LOGIX_DEV_MODE", "0")
    os.environ.setdefault("ADMIN_EMAILS", ns.admin_email)
    os.environ.setdefault("LOGIX_ADMIN_PASSWORD", "placeholder-for-schema-init")
    os.environ.setdefault("LOGIX_INGEST_API_KEY", "placeholder-for-schema-init")
    import main  # noqa: E402

    main.init_db()
    main.init_control_tables()
    ok(f"clean database created at {DB_PATH.name}")

    password = secrets.token_urlsafe(24)
    ingest = secrets.token_hex(32)
    ENV_PATH.write_text(
        "# Logix production environment. Generated by ops/go_live.py.\n"
        "# Load this before starting the server. NEVER commit it.\n"
        "#\n"
        "# The admin password and ingest key below are the only shared secrets in\n"
        "# the system. Rotate them by re-running `go_live.py init`.\n"
        "\n"
        "LOGIX_DEV_MODE=0\n"
        f"ADMIN_EMAILS={ns.admin_email}\n"
        f"LOGIX_ADMIN_PASSWORD={password}\n"
        f"LOGIX_INGEST_API_KEY={ingest}\n"
        "\n"
        "# Set once every workstation has enrolled -- the shared key above then\n"
        "# stops being accepted and only per-device keys work.\n"
        "LOGIX_REQUIRE_DEVICE_KEY=0\n"
        "\n"
        "# Browser origins allowed to call the API. Leave empty when the dashboard\n"
        "# is served from the same origin as the API (the normal setup).\n"
        "LOGIX_ALLOWED_ORIGINS=\n",
        encoding="utf-8",
    )
    try:
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass
    ok(f"secrets written to {ENV_PATH.name} (admin password + ingest key)")
    warn("read that file once, store the password in a manager, and keep it out of git")
    return 0


def cmd_register(ns) -> int:
    """Cut a hostname-pinned invite for every station in the list."""
    env = _read_env(ENV_PATH)
    sys.path.insert(0, str(SERVER))
    for k, v in env.items():
        os.environ.setdefault(k, v)
    import main  # noqa: E402

    entries = []
    for raw in Path(ns.devices).read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw or raw.startswith("#"):
            continue
        hostname, _, display = raw.partition(",")
        entries.append((hostname.strip(), display.strip() or hostname.strip()))

    if not entries:
        bad("no devices found in the list")
        return 1

    conn = main.get_db()
    now = datetime.now()
    expires = now + timedelta(minutes=main.INVITE_TTL_MINUTES)
    print(f"\n  {'HOSTNAME':<20} {'DISPLAY NAME':<26} INVITE CODE")
    print("  " + "-" * 74)
    try:
        for hostname, display in entries:
            code = "-".join(secrets.token_hex(2).upper() for _ in range(4))
            conn.execute(
                "INSERT INTO enrollment_invites "
                "(invite_code, category, display_name, note, created_by, created_at, "
                " expires_at, hostname) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (code, ns.category, display, "pre-registered via go_live.py",
                 env.get("ADMIN_EMAILS", "setup"), now.isoformat(), expires.isoformat(), hostname),
            )
            print(f"  {hostname:<20} {display:<26} {code}")
        conn.commit()
    finally:
        conn.close()

    print()
    ok(f"{len(entries)} invite(s) issued, each pinned to its hostname")
    warn(f"they expire at {expires.strftime('%H:%M:%S')} ({main.INVITE_TTL_MINUTES} minutes)")
    print(
        "\n  Enter a code in that machine's Logix client. A code will be refused on\n"
        "  any other hostname, so it is safe to print this table and walk the lab.\n"
    )
    return 0


def cmd_lockdown(ns) -> int:
    env = _read_env(ENV_PATH)
    if not ENV_PATH.exists():
        bad(f"{ENV_PATH.name} not found -- run `init` first")
        return 1

    sys.path.insert(0, str(SERVER))
    for k, v in env.items():
        os.environ.setdefault(k, v)
    import main  # noqa: E402

    conn = main.get_db()
    try:
        total = conn.execute("SELECT COUNT(*) FROM devices").fetchone()[0]
        enrolled = conn.execute(
            "SELECT COUNT(*) FROM devices WHERE api_key IS NOT NULL"
        ).fetchone()[0]
    finally:
        conn.close()

    print(f"\n  {enrolled} of {total} registered device(s) hold their own key.\n")
    if enrolled < total:
        bad("not every device has enrolled yet")
        print(
            "  Locking down now would cut off the ones that have not. Finish\n"
            "  enrolling them, or revoke the stragglers, then re-run.\n"
        )
        return 1

    text = ENV_PATH.read_text(encoding="utf-8").replace(
        "LOGIX_REQUIRE_DEVICE_KEY=0", "LOGIX_REQUIRE_DEVICE_KEY=1"
    )
    ENV_PATH.write_text(text, encoding="utf-8")
    ok("LOGIX_REQUIRE_DEVICE_KEY=1 -- the shared ingest key is now inert")
    warn("restart the server for this to take effect")
    return 0


def cmd_check(ns) -> int:
    """Report the posture without changing anything."""
    env = _read_env(ENV_PATH)
    merged = {**env, **{k: v for k, v in os.environ.items() if k.startswith(("LOGIX_", "ADMIN_"))}}
    problems = 0

    print("\n  Configuration")
    if merged.get("LOGIX_DEV_MODE") == "1":
        bad("LOGIX_DEV_MODE=1 -- passwordless dev-login is enabled. Never on a shared server.")
        problems += 1
    else:
        ok("dev mode off")

    pw = merged.get("LOGIX_ADMIN_PASSWORD", "")
    if not pw:
        bad("LOGIX_ADMIN_PASSWORD unset -- admin login would be permanently closed")
        problems += 1
    elif len(pw) < MIN_PASSWORD_LEN:
        warn(f"admin password is {len(pw)} chars; {MIN_PASSWORD_LEN}+ recommended")
    else:
        ok(f"admin password set ({len(pw)} chars)")

    if not merged.get("ADMIN_EMAILS", "").strip():
        bad("ADMIN_EMAILS unset -- nobody could sign in")
        problems += 1
    else:
        ok(f"admin allowlist: {merged['ADMIN_EMAILS']}")

    if merged.get("LOGIX_REQUIRE_DEVICE_KEY") == "1":
        ok("device-key-only mode ON (shared ingest key is inert)")
    elif merged.get("LOGIX_INGEST_API_KEY", "").strip():
        warn("shared ingest key still accepted -- run `lockdown` once every device has enrolled")
    else:
        bad("no ingest key and not in device-key-only mode -- agents cannot authenticate")
        problems += 1

    print("\n  Data")
    if not DB_PATH.exists():
        warn("no database yet (it is created on first start)")
    else:
        conn = sqlite3.connect(DB_PATH)
        try:
            count = lambda t: conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
            devices = count("devices")
            loadtest = conn.execute(
                "SELECT COUNT(*) FROM devices WHERE hostname LIKE 'LOADTEST%' "
                "OR hostname LIKE '%TEST%'"
            ).fetchone()[0]
            sessions = count("physical_log")
            print(f"       {devices} devices, {sessions} session rows, {count('alerts')} alerts")
            if loadtest:
                bad(f"{loadtest} device(s) look like test fixtures -- start from a clean DB")
                problems += 1
            else:
                ok("no obvious test fixtures in the device registry")
        except sqlite3.Error as e:
            warn(f"could not inspect the database: {e}")
        finally:
            conn.close()

    print("\n  Transport")
    warn("the server speaks plain HTTP -- put it behind a TLS reverse proxy "
         "(see docs/deploy/Caddyfile). Without it, the admin password and every "
         "device key cross the network in the clear.")

    print()
    if problems:
        bad(f"{problems} blocking issue(s) -- not ready for production")
        return 1
    ok("no blocking issues found")
    return 0


def main_cli() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    p_init = sub.add_parser("init", help="clean database + generated secrets")
    p_init.add_argument("--admin-email", required=True)
    p_init.add_argument("--force", action="store_true", help="archive an existing database")
    p_init.set_defaults(fn=cmd_init)

    p_reg = sub.add_parser("register", help="pre-register workstations (hostname-pinned invites)")
    p_reg.add_argument("--devices", required=True, help="text file: hostname[,display name] per line")
    p_reg.add_argument("--category", default="lab_workstation")
    p_reg.set_defaults(fn=cmd_register)

    p_lock = sub.add_parser("lockdown", help="require per-device keys (disable the shared key)")
    p_lock.set_defaults(fn=cmd_lockdown)

    p_chk = sub.add_parser("check", help="report the production posture")
    p_chk.set_defaults(fn=cmd_check)

    ns = p.parse_args()
    return ns.fn(ns)


if __name__ == "__main__":
    raise SystemExit(main_cli())
