; ============================================================================
; Logix Agent — official Windows wizard installer (Inno Setup 6).
;
; Produces a single LogixAgentSetup.exe that deploys the sign-in/timer agent,
; installs AnyDesk 7 (for the dashboard "Remote" action), lays down the native
; Python logging core, collects the central-server settings, registers the
; non-elevated monitor scheduled task, and starts it. Runs elevated end-to-end.
;
; BUILD:  compile this file with Inno Setup 6 (ISCC.exe logix-agent.iss) — see
;         installer\README.md. Output lands in installer\Output\.
;
; Layout it installs:
;   C:\Program Files\Logix\      <- agent scripts + AnyDesk installer (read-only)
;   C:\ProgramData\Logix\        <- native Python core (log_physical.py, paths.py)
;   C:\ProgramData\MindLabLogbook\ <- runtime state (created by the agent)
; ============================================================================

#define AppName "Logix Agent"
#define AppVersion "1.0.0"
#define AppPublisher "MindLab"
#define SrcRoot ".."
; Mascot branding, generated by installer\build_branding.py from a single
; artwork file (installer\branding\mascot-source.png). Everything below is
; guarded by #if FileExists so a checkout that never ran the branding step
; still compiles -- Inno just uses its stock wizard images.
#define BrandDir "branding"
#define BrandBase AddBackslash(SourcePath) + BrandDir + "\"

[Setup]
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
; Agent scripts hardcode C:\Program Files\Logix, so the location is fixed.
DefaultDirName={commonpf64}\Logix
DisableDirPage=yes
DisableProgramGroupPage=yes
; Snappier, Comnyang-style minimal flow: skip the extra "ready to install"
; confirmation page -- the one custom page (server settings) already gates the
; only decision the operator makes.
DisableReadyPage=yes
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
OutputDir=Output
OutputBaseFilename=LogixAgentSetup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName={#AppName}
#if FileExists(BrandBase + "logix.ico")
SetupIconFile={#BrandDir}\logix.ico
UninstallDisplayIcon={app}\logix.ico
#endif
#if FileExists(BrandBase + "wizard-image.bmp")
WizardImageFile={#BrandDir}\wizard-image.bmp
#endif
#if FileExists(BrandBase + "wizard-small.bmp")
WizardSmallImageFile={#BrandDir}\wizard-small.bmp
#endif

[Languages]
; EN/ID picker (Comnyang-style). Inno shows a language-select dialog at launch
; whenever more than one language is defined. Indonesian.isl ships alongside
; this script (Inno has no bundled Indonesian).
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "id"; MessagesFile: "Indonesian.isl"

[Messages]
; Warm, on-brand copy per language so the wizard reads like a product. The
; mascot shows on the Welcome/Finished pages via WizardImageFile above.
en.SetupAppTitle=Logix
id.SetupAppTitle=Logix
en.SetupWindowTitle=Logix Setup
id.SetupWindowTitle=Pemasangan Logix
en.WelcomeLabel1=Welcome to Logix
id.WelcomeLabel1=Selamat datang di Logix
en.WelcomeLabel2=This sets up the Logix agent on this computer: the sign-in logbook, session timer, AnyDesk for remote help, and monitoring.%n%nIt only takes a moment. Click Next to continue.
id.WelcomeLabel2=Ini memasang agen Logix di komputer ini: logbook sign-in, timer sesi, AnyDesk untuk bantuan jarak jauh, dan monitoring.%n%nHanya sebentar. Klik Berikutnya untuk melanjutkan.
en.FinishedHeadingLabel=Logix is ready
id.FinishedHeadingLabel=Logix siap digunakan
en.FinishedLabel=The Logix agent is installed and running. Lock and unlock this PC to see the sign-in screen, and the device shows up on the dashboard within a few seconds.
id.FinishedLabel=Agen Logix sudah terpasang dan berjalan. Kunci lalu buka kembali PC ini untuk melihat layar sign-in, dan perangkat akan muncul di dashboard dalam beberapa detik.
en.FinishedLabelNoIcons=The Logix agent is installed and running. Lock and unlock this PC to see the sign-in screen, and the device shows up on the dashboard within a few seconds.
id.FinishedLabelNoIcons=Agen Logix sudah terpasang dan berjalan. Kunci lalu buka kembali PC ini untuk melihat layar sign-in, dan perangkat akan muncul di dashboard dalam beberapa detik.

[CustomMessages]
; Strings for the bespoke server-settings page and the two validation prompts,
; read from [Code] via {cm:...} so they follow the selected language.
en.CfgCaption=Connect to your Logix server
id.CfgCaption=Hubungkan ke server Logix
en.CfgDesc=Tell this device where the dashboard lives.
id.CfgDesc=Beri tahu perangkat ini di mana dashboard berada.
en.CfgBody=These are saved to C:\ProgramData\Logix\config.env and can be changed later. Ask your Logix admin for the server address and key.
id.CfgBody=Data ini disimpan di C:\ProgramData\Logix\config.env dan bisa diubah nanti. Minta alamat server dan kunci ke admin Logix.
en.CfgUrl=Server URL (e.g. https://logix.example.org):
id.CfgUrl=URL Server (mis. https://logix.example.org):
en.CfgKey=Server API key (the ingest key from your server):
id.CfgKey=Kunci API server (ingest key dari server kamu):
en.CfgDevice=Device name (leave blank to use this PC's name):
id.CfgDevice=Nama perangkat (kosongkan untuk memakai nama PC ini):
en.CfgNeedUrl=Please enter the Logix server URL (e.g. https://logix.example.org).
id.CfgNeedUrl=Masukkan URL server Logix (mis. https://logix.example.org).
en.CfgNeedKey=Please enter the server API key (the ingest key from your Logix server).
id.CfgNeedKey=Masukkan kunci API server (ingest key dari server Logix kamu).
en.PyMissing=Logix installed. Note: Python 3 was not found on PATH. The agent runs fine, but local session logging (log_physical.py) needs Python 3 - install it from python.org to enable it.
id.PyMissing=Logix terpasang. Catatan: Python 3 tidak ditemukan di PATH. Agen tetap berjalan, tapi pencatatan sesi lokal (log_physical.py) butuh Python 3 - pasang dari python.org untuk mengaktifkannya.

[Files]
; Agent scripts -> C:\Program Files\Logix. Exclude the dev/test harnesses
; (test_*.ps1, preview_popup.ps1) -- they're for the repo, not client PCs.
Source: "{#SrcRoot}\windows\*.ps1"; DestDir: "{app}"; Excludes: "test_*.ps1,preview_popup.ps1"; Flags: ignoreversion
; AnyDesk installer bundled so setup can deploy it silently
Source: "assets\anydesk-7-0-0.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Optional branding logo (popup uses C:\Program Files\Logix\logo.png)
Source: "{#SrcRoot}\windows\logo.png"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Mascot icon, kept alongside the app so Add/Remove Programs shows it too.
Source: "{#BrandDir}\logix.ico"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Native Python logging core -> C:\ProgramData\Logix (Get-LogixCoreDir default)
Source: "{#SrcRoot}\logix\log_physical.py"; DestDir: "{commonappdata}\Logix"; Flags: ignoreversion
Source: "{#SrcRoot}\logix\paths.py"; DestDir: "{commonappdata}\Logix"; Flags: ignoreversion

[Run]
; Register the monitor task (non-elevated principal), install AnyDesk, write
; config.env from the wizard inputs, and start the agent -- all unattended.
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\install_logbook_tasks.ps1"" -NonInteractive -RunNow -ServerUrl ""{code:GetServerUrl}"" -ServerApiKey ""{code:GetServerKey}"" -DeviceName ""{code:GetDeviceName}"" -AnyDeskInstaller ""{app}\anydesk-7-0-0.exe"""; \
  StatusMsg: "Registering Logix agent, installing AnyDesk, starting monitor..."; \
  Flags: runhidden waituntilterminated

[UninstallRun]
; Best-effort teardown: stop the monitor and unregister the task.
Filename: "schtasks.exe"; Parameters: "/End /TN ""MindLab Report Logbook Monitor"""; Flags: runhidden; RunOnceId: "StopTask"
Filename: "schtasks.exe"; Parameters: "/Delete /TN ""MindLab Report Logbook Monitor"" /F"; Flags: runhidden; RunOnceId: "DelTask"

[Code]
var
  ConfigPage: TInputQueryWizardPage;

procedure InitializeWizard;
begin
  // Strings come from [CustomMessages] via {cm:...} so the page follows the
  // language picked at launch (EN/ID).
  ConfigPage := CreateInputQueryPage(wpSelectDir,
    ExpandConstant('{cm:CfgCaption}'),
    ExpandConstant('{cm:CfgDesc}'),
    ExpandConstant('{cm:CfgBody}'));
  ConfigPage.Add(ExpandConstant('{cm:CfgUrl}'), False);
  ConfigPage.Add(ExpandConstant('{cm:CfgKey}'), False);
  ConfigPage.Add(ExpandConstant('{cm:CfgDevice}'), False);
  ConfigPage.Values[0] := 'http://localhost:8000';
end;

// Don't let the operator continue with an empty server URL or key -- a device
// that can't reach the server or authenticate is a silent dead-end otherwise.
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = ConfigPage.ID then
  begin
    if Trim(ConfigPage.Values[0]) = '' then
    begin
      MsgBox(ExpandConstant('{cm:CfgNeedUrl}'), mbError, MB_OK);
      Result := False;
    end
    else if Trim(ConfigPage.Values[1]) = '' then
    begin
      MsgBox(ExpandConstant('{cm:CfgNeedKey}'), mbError, MB_OK);
      Result := False;
    end;
  end;
end;

function GetServerUrl(Param: string): string;
begin
  Result := Trim(ConfigPage.Values[0]);
end;

function GetServerKey(Param: string): string;
begin
  Result := Trim(ConfigPage.Values[1]);
end;

function GetDeviceName(Param: string): string;
begin
  Result := Trim(ConfigPage.Values[2]);
end;

// Warn (don't block) if no Python is on PATH -- the sign-in/timer/lock/remote
// features are pure PowerShell and work regardless, but the local session-log
// bridge (log_physical.py) needs Python 3.
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    if not Exec('cmd.exe', '/c where python || where py', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then
      MsgBox(ExpandConstant('{cm:PyMissing}'), mbInformation, MB_OK);
  end;
end;
