; ============================================================================
; Logix Agent — official Windows wizard installer (Inno Setup 6).
;
; Produces a single LogixAgentSetup.exe that deploys the sign-in/timer agent,
; installs AnyDesk 7 (for the dashboard "Remote" action), lays down the native
; Python logging core, collects the central-server settings, registers the
; non-elevated monitor scheduled task, and starts it. Runs elevated end-to-end.
;
; BUILD:  compile this file with Inno Setup 6 (ISCC.exe logix-agent.iss) — see
;         installer\README.md. Output lands in installer\Output\.
;
; Layout it installs:
;   C:\Program Files\Logix\      <- agent scripts + AnyDesk installer (read-only)
;   C:\ProgramData\Logix\        <- native Python core (log_physical.py, paths.py)
;   C:\ProgramData\Logix\ <- runtime state (created by the agent)
; ============================================================================

#define AppName "Logix Agent"
#define AppVersion "1.2.1"
#define AppPublisher "Logix"
#define SrcRoot ".."
; Mascot branding, generated by installer\build_branding.py from a single
; artwork file (installer\branding\mascot-source.png). Everything below is
; guarded by #if FileExists so a checkout that never ran the branding step
; still compiles -- Inno just uses its stock wizard images.
#define BrandDir "branding"
#define BrandBase AddBackslash(SourcePath) + BrandDir + "\"

[Setup]
; Fixed AppId so every future version upgrades THIS install entry instead of
; stacking a second "Logix Agent" in Add/Remove Programs. Never change it.
AppId={{B7A0C1D4-5E2F-4A63-9C58-1F0D2E7A8B3C}
AppName={#AppName}
AppVersion={#AppVersion}
VersionInfoVersion={#AppVersion}
AppPublisher={#AppPublisher}
; Agent scripts hardcode C:\Program Files\Logix, so the location is fixed.
DefaultDirName={commonpf64}\Logix
DisableDirPage=yes
DisableProgramGroupPage=yes
; Snappier, Comnyang-style minimal flow: skip the extra "ready to install"
; confirmation page -- the one custom page (server settings) already gates the
; only decision the operator makes.
DisableReadyPage=yes
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
OutputDir=Output
OutputBaseFilename=LogixAgentSetup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName={#AppName}
#if FileExists(BrandBase + "logix.ico")
SetupIconFile={#BrandDir}\logix.ico
UninstallDisplayIcon={app}\logix.ico
#endif
#if FileExists(BrandBase + "wizard-image.bmp")
WizardImageFile={#BrandDir}\wizard-image.bmp
#endif
#if FileExists(BrandBase + "wizard-small.bmp")
WizardSmallImageFile={#BrandDir}\wizard-small.bmp
#endif

[Languages]
; EN/ID picker (Comnyang-style). Inno shows a language-select dialog at launch
; whenever more than one language is defined. Indonesian.isl ships alongside
; this script (Inno has no bundled Indonesian).
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "id"; MessagesFile: "Indonesian.isl"

[Messages]
; Warm, on-brand copy per language so the wizard reads like a product. The
; mascot shows on the Welcome/Finished pages via WizardImageFile above.
en.SetupAppTitle=Logix
id.SetupAppTitle=Logix
en.SetupWindowTitle=Logix Setup
id.SetupWindowTitle=Pemasangan Logix
en.WelcomeLabel1=Welcome to Logix
id.WelcomeLabel1=Selamat datang di Logix
en.WelcomeLabel2=This sets up the Logix agent on this computer: the sign-in logbook, session timer, AnyDesk for remote help, and monitoring.%n%nIt only takes a moment. Click Next to continue.
id.WelcomeLabel2=Ini memasang agen Logix di komputer ini: logbook sign-in, timer sesi, AnyDesk untuk bantuan jarak jauh, dan monitoring.%n%nHanya sebentar. Klik Berikutnya untuk melanjutkan.
en.FinishedHeadingLabel=Logix is ready
id.FinishedHeadingLabel=Logix siap digunakan
en.FinishedLabel=The Logix agent is installed and running. Lock and unlock this PC to see the sign-in screen, and the device shows up on the dashboard within a few seconds.
id.FinishedLabel=Agen Logix sudah terpasang dan berjalan. Kunci lalu buka kembali PC ini untuk melihat layar sign-in, dan perangkat akan muncul di dashboard dalam beberapa detik.
en.FinishedLabelNoIcons=The Logix agent is installed and running. Lock and unlock this PC to see the sign-in screen, and the device shows up on the dashboard within a few seconds.
id.FinishedLabelNoIcons=Agen Logix sudah terpasang dan berjalan. Kunci lalu buka kembali PC ini untuk melihat layar sign-in, dan perangkat akan muncul di dashboard dalam beberapa detik.

[CustomMessages]
; Strings for the bespoke server-settings page and the two validation prompts,
; read from [Code] via {cm:...} so they follow the selected language.
en.CfgCaption=Connect to your Logix server
id.CfgCaption=Hubungkan ke server Logix
en.CfgDesc=Tell this device where the dashboard lives.
id.CfgDesc=Beri tahu perangkat ini di mana dashboard berada.
en.CfgBody=These are saved to C:\ProgramData\Logix\config.env and can be changed later. Ask your Logix admin for the server address and key.
id.CfgBody=Data ini disimpan di C:\ProgramData\Logix\config.env dan bisa diubah nanti. Minta alamat server dan kunci ke admin Logix.
en.CfgUrl=Server URL (e.g. https://logix.example.org):
id.CfgUrl=URL Server (mis. https://logix.example.org):
en.CfgKey=Server API key (the ingest key from your server):
id.CfgKey=Kunci API server (ingest key dari server kamu):
en.CfgDevice=Device name (leave blank to use this PC's name):
id.CfgDevice=Nama perangkat (kosongkan untuk memakai nama PC ini):
en.CfgInvite=Enrollment code (from the dashboard; recommended):
id.CfgInvite=Kode pendaftaran (dari dashboard; disarankan):
en.CfgNeedUrl=Please enter the Logix server URL (e.g. https://logix.example.org).
id.CfgNeedUrl=Masukkan URL server Logix (mis. https://logix.example.org).
en.CfgNeedKey=Please enter the server API key (the ingest key from your Logix server).
id.CfgNeedKey=Masukkan kunci API server (ingest key dari server Logix kamu).
en.PyMissing=Logix installed. Note: Python 3 was not found on PATH. The agent runs fine, but local session logging (log_physical.py) needs Python 3 - install it from python.org to enable it.
id.PyMissing=Logix terpasang. Catatan: Python 3 tidak ditemukan di PATH. Agen tetap berjalan, tapi pencatatan sesi lokal (log_physical.py) butuh Python 3 - pasang dari python.org untuk mengaktifkannya.
; The YASB task (see [Tasks] below) is offered ONLY when YasbConfigDetected
; finds an existing ~\.config\yasb\config.yaml -- so this copy always speaks
; to someone who already runs YASB, never introduces it as something new.
en.TaskYasbGroup=Optional
id.TaskYasbGroup=Opsional
en.TaskYasb=Integrate with YASB (detected on this PC) - moves the session timer into your status bar instead of the floating pill
id.TaskYasb=Integrasikan dengan YASB (terdeteksi di PC ini) - memindahkan timer sesi ke status bar, bukan pil mengambang
en.YasbDone=YASB integration is set up. Logix will show a compact widget in your bar; the pill is hidden. One manual step remains: paste the widget snippet into config.yaml.%n%nThe snippet was written to:%n%1
id.YasbDone=Integrasi YASB sudah siap. Logix akan tampil sebagai widget ringkas di bar kamu; pil mengambang disembunyikan. Masih ada satu langkah manual: tempel potongan widget ke config.yaml.%n%nPotongannya sudah ditulis ke:%n%1

[Files]
; Agent scripts -> C:\Program Files\Logix. Exclude the dev/test harnesses and
; repo-side installers (test_*.ps1, preview_*.ps1, bootstrap-client.ps1) --
; they're for the repo, not client PCs.
Source: "{#SrcRoot}\windows\*.ps1"; DestDir: "{app}"; Excludes: "test_*.ps1,preview_*.ps1,bootstrap-client.ps1"; Flags: ignoreversion
; AnyDesk installer bundled so setup can deploy it silently
Source: "assets\anydesk-7-0-0.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Optional branding logo (popup uses C:\Program Files\Logix\logo.png)
Source: "{#SrcRoot}\windows\logo.png"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Mascot icon, kept alongside the app so Add/Remove Programs shows it too.
Source: "{#BrandDir}\logix.ico"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Native Python logging core -> C:\ProgramData\Logix (Get-LogixCoreDir default)
Source: "{#SrcRoot}\logix\log_physical.py"; DestDir: "{commonappdata}\Logix"; Flags: ignoreversion
Source: "{#SrcRoot}\logix\paths.py"; DestDir: "{commonappdata}\Logix"; Flags: ignoreversion
; Reporting core. Without these two a Logix Device can record sessions and
; then not show them, which is most of the way to not being a product: the
; report shortcut below resolves report_server.py out of this directory, and
; report_server.py drives logbook_report.py for both the table and the export.
Source: "{#SrcRoot}\logix\logbook_report.py"; DestDir: "{commonappdata}\Logix"; Flags: ignoreversion
Source: "{#SrcRoot}\logix\report_server.py"; DestDir: "{commonappdata}\Logix"; Flags: ignoreversion
; Workstation telemetry (CPU/memory/GPU/storage) for the dashboard's health
; panel. Optional in behaviour -- report_server.py imports it in a try/except
; and the panel renders "Unavailable" without it -- but not shipping the file
; at all means the panel is ALWAYS unavailable on a fresh install, which is a
; deployment gap, not the graceful degradation the module is designed for.
Source: "{#SrcRoot}\logix\workstation.py"; DestDir: "{commonappdata}\Logix"; Flags: ignoreversion

[Tasks]
; Shown ONLY when YasbConfigDetected finds an existing YASB config on this
; machine (see [Code]) -- Inno hides a [Tasks] entry entirely when Check:
; returns False, so someone who has never heard of YASB never sees this.
; Checked by default: detection means YASB is already how this person works,
; so integrating is the expected choice, not a change being pushed on them.
; It stays a real checkbox they can clear, per the product rule that YASB is
; an optional resource Logix must work perfectly without.
Name: "yasbintegrate"; Description: "{cm:TaskYasb}"; GroupDescription: "{cm:TaskYasbGroup}"; Check: YasbConfigDetected

[Icons]
; The two things a device owner does outside a session. Both were reachable
; only from a command line before, which for the person actually using a lab
; workstation means not reachable at all.
Name: "{group}\Laporan Logix"; \
    Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; \
    Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\logix_reports.ps1"""; \
    IconFilename: "{app}\logix.ico"; Comment: "Lihat dan ekspor riwayat sesi komputer ini"
Name: "{group}\Koneksi Server Logix"; \
    Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; \
    Parameters: "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ""{app}\logix_server.ps1"""; \
    IconFilename: "{app}\logix.ico"; Comment: "Hubungkan atau putuskan perangkat ini dari Logix Server"

[Run]
; Register the monitor task (non-elevated principal), install AnyDesk, write
; config.env from the wizard inputs, and start the agent -- all unattended.
; conhost --headless: on Windows 11 the default console host is Windows
; Terminal, which can flash a visible terminal tab for a hidden powershell
; launch; the headless wrapper never creates a window (see
; Start-HiddenPowerShell in logbook_common.ps1).
Filename: "{sys}\conhost.exe"; \
  Parameters: "--headless powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""{app}\install_logbook_tasks.ps1"" -NonInteractive -RunNow -ServerUrl ""{code:GetServerUrl}"" -ServerApiKey ""{code:GetServerKey}"" -DeviceName ""{code:GetDeviceName}"" -InviteCode ""{code:GetInviteCode}"" -ServerCertPath ""{code:GetServerCert}"" -AnyDeskInstaller ""{app}\anydesk-7-0-0.exe"""; \
  StatusMsg: "Registering Logix agent, installing AnyDesk, starting monitor..."; \
  Flags: runhidden waituntilterminated

; Only runs when the yasbintegrate task is checked (see [Tasks]), which itself
; only appears when YASB was already detected. -Enable switches the widget to
; 'bar' posture (floating pill draws nothing) and writes the paste-in widget
; snippet to %TEMP%\logix-yasb-snippet.txt -- it deliberately does NOT edit
; config.yaml itself (see logix_yasb.ps1's header comment: that file is
; hand-tuned and no YAML library round-trips it cleanly), so this step alone
; does not finish the job. The CurStepChanged handler below points the
; operator at that file once this has run.
Filename: "{sys}\conhost.exe"; \
  Parameters: "--headless powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""{app}\logix_yasb.ps1"" -Enable"; \
  StatusMsg: "Integrating with YASB..."; \
  Flags: runhidden waituntilterminated; Tasks: yasbintegrate

[UninstallRun]
; Best-effort teardown: stop the monitor, unregister the task, and drop the
; HKCU Run fallback install_logbook_tasks.ps1 registers (must match the value
; name there). Runs as the uninstalling admin's HKCU -- same account that
; installed, in the single-operator lab setup this targets.
Filename: "schtasks.exe"; Parameters: "/End /TN ""Logix Agent Monitor"""; Flags: runhidden; RunOnceId: "StopTask"
Filename: "schtasks.exe"; Parameters: "/Delete /TN ""Logix Agent Monitor"" /F"; Flags: runhidden; RunOnceId: "DelTask"
Filename: "reg.exe"; Parameters: "delete ""HKCU\Software\Microsoft\Windows\CurrentVersion\Run"" /v LogixAgentMonitor /f"; Flags: runhidden; RunOnceId: "DelRunKey"

[Code]
var
  ConfigPage: TInputQueryWizardPage;

// Command-line overrides, so a lab can be imaged unattended instead of an
// operator typing the same server URL into a wizard on every workstation:
//
//   LogixAgentSetup.exe /VERYSILENT /SUPPRESSMSGBOXES ^
//     /SERVERURL="https://logix.lab.example" /SERVERKEY="..." /DEVICENAME="WS-07 - GPU-A100"
//
// A value given on the command line always wins; anything omitted falls back
// to the wizard page, so the interactive install is unchanged.
function ParamOr(const Name, Fallback: string): string;
var
  v: string;
begin
  v := Trim(ExpandConstant('{param:' + Name + '|}'));
  if v = '' then
    v := Fallback;
  Result := v;
end;

// Gate for the yasbintegrate [Tasks] entry. YASB (Reborn) has no registry
// footprint and may not be running at install time, so a process check would
// miss the common case of "installed but not launched yet". config.yaml is
// the one artifact YASB always creates before it can run at all, and it is
// the exact path logix_yasb.ps1 itself already treats as the install marker
// (see its own $yasbConfig) -- one definition of "YASB is here", not two.
//
// %USERPROFILE%, not {userappdata}: .config lives directly under the profile
// root, not under Roaming AppData. This installer runs elevated via a normal
// UAC prompt (not a different-user launch), so the token's own environment
// still resolves to the operator's own profile -- the same assumption
// install_logbook_tasks.ps1 already makes for the invoking user's SID.
function YasbConfigDetected(): Boolean;
begin
  Result := FileExists(ExpandConstant('{%USERPROFILE}') + '\.config\yasb\config.yaml');
end;

procedure InitializeWizard;
begin
  // Strings come from [CustomMessages] via {cm:...} so the page follows the
  // language picked at launch (EN/ID).
  ConfigPage := CreateInputQueryPage(wpSelectDir,
    ExpandConstant('{cm:CfgCaption}'),
    ExpandConstant('{cm:CfgDesc}'),
    ExpandConstant('{cm:CfgBody}'));
  ConfigPage.Add(ExpandConstant('{cm:CfgUrl}'), False);
  ConfigPage.Add(ExpandConstant('{cm:CfgKey}'), False);
  ConfigPage.Add(ExpandConstant('{cm:CfgDevice}'), False);
  ConfigPage.Add(ExpandConstant('{cm:CfgInvite}'), False);
  ConfigPage.Values[0] := 'http://localhost:8000';
end;

// Don't let the operator continue with an empty server URL or key -- a device
// that can't reach the server or authenticate is a silent dead-end otherwise.
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = ConfigPage.ID then
  begin
    // Nothing to validate when the values came from the command line -- and in
    // a silent install there is no operator to answer a message box, which
    // would otherwise abort setup with no page ever shown.
    if (ParamOr('ServerUrl', '') <> '') and
       ((ParamOr('ServerKey', '') <> '') or (ParamOr('InviteCode', '') <> '')) then
      Exit;
    if Trim(ConfigPage.Values[0]) = '' then
    begin
      MsgBox(ExpandConstant('{cm:CfgNeedUrl}'), mbError, MB_OK);
      Result := False;
    end
    else if (Trim(ConfigPage.Values[1]) = '') and (Trim(ConfigPage.Values[3]) = '') then
    begin
      // Either credential is enough: an enrollment code (preferred -- the
      // device ends up with a key of its own) or the shared ingest key.
      MsgBox(ExpandConstant('{cm:CfgNeedKey}'), mbError, MB_OK);
      Result := False;
    end;
  end;
end;

function GetServerUrl(Param: string): string;
begin
  Result := ParamOr('ServerUrl', Trim(ConfigPage.Values[0]));
end;

function GetServerKey(Param: string): string;
begin
  Result := ParamOr('ServerKey', Trim(ConfigPage.Values[1]));
end;

function GetDeviceName(Param: string): string;
begin
  Result := ParamOr('DeviceName', Trim(ConfigPage.Values[2]));
end;

// One-time enrollment code. With it the device performs a real handshake and
// receives its own key; without it, it falls back to the shared bootstrap key.
function GetInviteCode(Param: string): string;
begin
  Result := ParamOr('InviteCode', Trim(ConfigPage.Values[3]));
end;

// Path to the server's certificate, for a lab server that issues its own.
// Nothing to import when the server has a public certificate.
function GetServerCert(Param: string): string;
begin
  Result := ParamOr('ServerCert', '');
end;

// Warn (don't block) if no Python is on PATH -- the sign-in/timer/lock/remote
// features are pure PowerShell and work regardless, but the local session-log
// bridge (log_physical.py) needs Python 3.
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  SnippetPath: string;
begin
  if CurStep = ssPostInstall then
  begin
    if not Exec('cmd.exe', '/c where python || where py', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then
      MsgBox(ExpandConstant('{cm:PyMissing}'), mbInformation, MB_OK);

    // The [Run] step for yasbintegrate runs hidden, so its own Write-Host
    // instructions are never seen -- this is the one place left to tell the
    // operator that the widget snippet still needs a manual paste into their
    // (deliberately untouched) config.yaml.
    //
    // The snippet path is built into its own array first rather than inline
    // in the FmtMessage call: a continuation line whose first non-blank
    // character is '[' gets misread as a section header by Inno's own
    // line scanner, even here inside [Code].
    if WizardIsTaskSelected('yasbintegrate') then
    begin
      SnippetPath := ExpandConstant('{%TEMP}') + '\logix-yasb-snippet.txt';
      MsgBox(FmtMessage(ExpandConstant('{cm:YasbDone}'), [SnippetPath]), mbInformation, MB_OK);
    end;
  end;
end;
